
#include <app/vector_student.h>

FUNC_VECTOR_NEW_IMPL(student)

FUNC_VECTOR_DELETE_IMPL(student)

FUNC_VECTOR_AT_IMPL(student)

FUNC_VECTOR_FRONT_IMPL(student)

FUNC_VECTOR_BACK_IMPL(student)

FUNC_VECTOR_DATA_IMPL(student)

FUNC_VECTOR_EMPTY_IMPL(student)

FUNC_VECTOR_SIZE_IMPL(student)

FUNC_VECTOR_MAX_SIZE_IMPL(student)

FUNC_VECTOR_CLEAR_IMPL(student)

FUNC_VECTOR_INSERT_IMPL(student)

FUNC_VECTOR_PUSH_BACK_IMPL(student)

FUNC_VECTOR_ERASE_IMPL(student)

FUNC_VECTOR_POP_BACK_IMPL(student)

FUNC_VECTOR_SWAP_IMPL(student)
