#pragma once

#include <stdlib.h>
#include <mvc/vector.h>

VECTOR_DEF(char);

FUNC_VECTOR_NEW(char);
FUNC_VECTOR_DELETE(char);
FUNC_VECTOR_AT(char);
FUNC_VECTOR_FRONT(char);
FUNC_VECTOR_BACK(char);
FUNC_VECTOR_DATA(char);
FUNC_VECTOR_EMPTY(char);
FUNC_VECTOR_SIZE(char);
FUNC_VECTOR_MAX_SIZE(char);
FUNC_VECTOR_CLEAR(char);
FUNC_VECTOR_INSERT(char);
FUNC_VECTOR_ERASE(char);
FUNC_VECTOR_PUSH_BACK(char);
FUNC_VECTOR_POP_BACK(char);
FUNC_VECTOR_SWAP(char);