
#include <app/vector_char.h>

FUNC_VECTOR_NEW_IMPL(char)

FUNC_VECTOR_DELETE_IMPL(char)

FUNC_VECTOR_AT_IMPL(char)

FUNC_VECTOR_FRONT_IMPL(char)

FUNC_VECTOR_BACK_IMPL(char)

FUNC_VECTOR_DATA_IMPL(char)

FUNC_VECTOR_EMPTY_IMPL(char)

FUNC_VECTOR_SIZE_IMPL(char)

FUNC_VECTOR_MAX_SIZE_IMPL(char)

FUNC_VECTOR_CLEAR_IMPL(char)

FUNC_VECTOR_INSERT_IMPL(char)

FUNC_VECTOR_PUSH_BACK_IMPL(char)

FUNC_VECTOR_ERASE_IMPL(char)

FUNC_VECTOR_POP_BACK_IMPL(char)

FUNC_VECTOR_SWAP_IMPL(char)
