
#include <app/vector_int.h>

FUNC_VECTOR_NEW_IMPL(element)

FUNC_VECTOR_DELETE_IMPL(element)

FUNC_VECTOR_AT_IMPL(element)

FUNC_VECTOR_FRONT_IMPL(element)

FUNC_VECTOR_BACK_IMPL(element)

FUNC_VECTOR_DATA_IMPL(element)

FUNC_VECTOR_EMPTY_IMPL(element)

FUNC_VECTOR_SIZE_IMPL(element)

FUNC_VECTOR_MAX_SIZE_IMPL(element)

FUNC_VECTOR_CLEAR_IMPL(element)

FUNC_VECTOR_INSERT_IMPL(element)

FUNC_VECTOR_PUSH_BACK_IMPL(element)

FUNC_VECTOR_ERASE_IMPL(element)

FUNC_VECTOR_POP_BACK_IMPL(element)

FUNC_VECTOR_SWAP_IMPL(element)
